/* Generated by the Nim Compiler v1.9.1 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI33554466 = {size: 0,kind: 1,base: null,node: null,finalizer: null};
var NTI721420302 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI973078606 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI973078612 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI134217745 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217751 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555171 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555179 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555178 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555175 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555176 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
var NNI33555176 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555176.node = NNI33555176;
NTI33555178.base = NTI33555175;
NTI33555179.base = NTI33555175;
var NNI33555175 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555178, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555179, name: "up", sons: null}]};
NTI33555175.node = NNI33555175;
var NNI33555171 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555171.node = NNI33555171;
NTI33555175.base = NTI33555171;
NTI33555176.base = NTI33555175;
NTI134217741.base = NTI33555176;
NTI134217743.base = NTI134217741;
var NNI134217751 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217751.node = NNI134217751;
NTI134217751.base = NTI33555176;
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
NTI134217749.base = NTI33555176;
var NNI134217745 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217745.node = NNI134217745;
NTI134217745.base = NTI33555176;
var NNI973078612 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "a", len: 0, typ: NTI973078606, name: "a", sons: null}, 
{kind: 1, offset: "b", len: 0, typ: NTI33554435, name: "b", sons: null}]};
NTI973078612.node = NNI973078612;
var NNI721420302 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554435, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554466, name: "Field1", sons: null}]};
NTI721420302.node = NNI721420302;

function mnewString(len_33556836) {
        return new Array(len_33556836);
  

  
}

function toJSStr(s_33556747) {
  var result_33556748 = null;

    var res_33556782 = newSeq_33556765((s_33556747).length);
    var i_33556783 = 0;
    var j_33556784 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556783 < (s_33556747).length)) break Label2;
          var c_33556785 = s_33556747[i_33556783];
          if ((c_33556785 < 128)) {
          res_33556782[j_33556784] = String.fromCharCode(c_33556785);
          i_33556783 += 1;
          }
          else {
            var helper_33556798 = newSeq_33556765(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556799 = c_33556785.toString(16);
                  if ((((code_33556799) == null ? 0 : (code_33556799).length) == 1)) {
                  helper_33556798.push("%0");;
                  }
                  else {
                  helper_33556798.push("%");;
                  }
                  
                  helper_33556798.push(code_33556799);;
                  i_33556783 += 1;
                  if ((((s_33556747).length <= i_33556783) || (s_33556747[i_33556783] < 128))) {
                  break Label3;
                  }
                  
                  c_33556785 = s_33556747[i_33556783];
                }
            };
++excHandler;
            try {
            res_33556782[j_33556784] = decodeURIComponent(helper_33556798.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            res_33556782[j_33556784] = helper_33556798.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556784 += 1;
        }
    };
    if (res_33556782.length < j_33556784) { for (var i = res_33556782.length ; i < j_33556784 ; ++i) res_33556782.push(null); }
               else { res_33556782.length = j_33556784; };
    result_33556748 = res_33556782.join("");

  return result_33556748;

}

function raiseException(e_33556607, ename_33556608) {
    e_33556607.name = ename_33556608;
    if ((excHandler == 0)) {
    unhandledException(e_33556607);
    }
    
    throw e_33556607;

  
}

function addInt(a_33556883, b_33556884) {
        var result = a_33556883 + b_33556884;
    checkOverflowInt(result);
    return result;
  

  
}

function chckRange(i_33557132, a_33557133, b_33557134) {
  var result_33557135 = 0;

  BeforeRet: {
    if (((a_33557133 <= i_33557132) && (i_33557132 <= b_33557134))) {
    result_33557135 = i_33557132;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  };

  return result_33557135;

}

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_33557083, src_33557084, ti_33557085) {
  var result_33557094 = null;

    switch (ti_33557085.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer_33557074(ti_33557085))) {
      result_33557094 = src_33557084;
      }
      else {
        result_33557094 = [src_33557084[0], src_33557084[1]];
      }
      
      break;
    case 19:
            if (dest_33557083 === null || dest_33557083 === undefined) {
        dest_33557083 = {};
      }
      else {
        for (var key in dest_33557083) { delete dest_33557083[key]; }
      }
      for (var key in src_33557084) { dest_33557083[key] = src_33557084[key]; }
      result_33557094 = dest_33557083;
    
      break;
    case 18:
    case 17:
      if (!((ti_33557085.base == null))) {
      result_33557094 = nimCopy(dest_33557083, src_33557084, ti_33557085.base);
      }
      else {
      if ((ti_33557085.kind == 17)) {
      result_33557094 = (dest_33557083 === null || dest_33557083 === undefined) ? {m_type: ti_33557085} : dest_33557083;
      }
      else {
        result_33557094 = (dest_33557083 === null || dest_33557083 === undefined) ? {} : dest_33557083;
      }
      }
      nimCopyAux(result_33557094, src_33557084, ti_33557085.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_33557084)) { 
        if(dest_33557083 === null || dest_33557083 === undefined || dest_33557083.length != src_33557084.length) {
          dest_33557083 = new src_33557084.constructor(src_33557084);
        } else {
          dest_33557083.set(src_33557084, 0);
        }
        result_33557094 = dest_33557083;
      } else {
        if (src_33557084 === null) {
          result_33557094 = null;
        }
        else {
          if (dest_33557083 === null || dest_33557083 === undefined || dest_33557083.length != src_33557084.length) {
            dest_33557083 = new Array(src_33557084.length);
          }
          result_33557094 = dest_33557083;
          for (var i = 0; i < src_33557084.length; ++i) {
            result_33557094[i] = nimCopy(result_33557094[i], src_33557084[i], ti_33557085.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_33557084 === null) {
        result_33557094 = null;
      }
      else {
        if (dest_33557083 === null || dest_33557083 === undefined || dest_33557083.length != src_33557084.length) {
          dest_33557083 = new Array(src_33557084.length);
        }
        result_33557094 = dest_33557083;
        for (var i = 0; i < src_33557084.length; ++i) {
          result_33557094[i] = nimCopy(result_33557094[i], src_33557084[i], ti_33557085.base);
        }
      }
    
      break;
    case 28:
            if (src_33557084 !== null) {
        result_33557094 = src_33557084.slice(0);
      }
    
      break;
    default: 
      result_33557094 = src_33557084;
      break;
    }

  return result_33557094;

}

function chckIndx(i_33557127, a_33557128, b_33557129) {
  var result_33557130 = 0;

  BeforeRet: {
    if (((a_33557128 <= i_33557127) && (i_33557127 <= b_33557129))) {
    result_33557130 = i_33557127;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_33557127, a_33557128, b_33557129);
    }
    
  };

  return result_33557130;

}

function makeNimstrLit(c_33556741) {
      var result = [];
  for (var i = 0; i < c_33556741.length; ++i) {
    result[i] = c_33556741.charCodeAt(i);
  }
  return result;
  

  
}

function subInt(a_33556887, b_33556888) {
        var result = a_33556887 - b_33556888;
    checkOverflowInt(result);
    return result;
  

  
}

function cstrToNimstr(c_33556744) {
      var ln = c_33556744.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_33556744.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_33556744.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}
var ConstSet2 = setConstr([65, 90]);
var ConstSet3 = setConstr(95, 32, 46);
var ConstSet4 = setConstr(95, 32, 46);

function mulInt(a_33556891, b_33556892) {
        var result = a_33556891 * b_33556892;
    checkOverflowInt(result);
    return result;
  

  
}
var ConstSet5 = setConstr([97, 122]);
var ConstSet6 = setConstr([65, 90], [97, 122]);
var ConstSet7 = setConstr([97, 122]);
var ConstSet8 = setConstr([65, 90]);
var ConstSet9 = setConstr([65, 90], [97, 122]);

function nimMax(a_33556941, b_33556942) {
    var Temporary1;

  var result_33556943 = 0;

  BeforeRet: {
    if ((b_33556942 <= a_33556941)) {
    Temporary1 = a_33556941;
    }
    else {
    Temporary1 = b_33556942;
    }
    
    result_33556943 = Temporary1;
    break BeforeRet;
  };

  return result_33556943;

}

function nimMin(a_33556937, b_33556938) {
    var Temporary1;

  var result_33556939 = 0;

  BeforeRet: {
    if ((a_33556937 <= b_33556938)) {
    Temporary1 = a_33556937;
    }
    else {
    Temporary1 = b_33556938;
    }
    
    result_33556939 = Temporary1;
    break BeforeRet;
  };

  return result_33556939;

}

function addChar(x_33557198, c_33557199) {
    x_33557198.push(c_33557199);

  
}
var objectID_1207959716 = [0];

function setTheme(theme_570425350) {
    document.documentElement.setAttribute("data-theme", theme_570425350);
    window.localStorage.setItem("theme", theme_570425350);

  
}
var Temporary1;
var t_570425369 = window.localStorage.getItem("theme");
if ((t_570425369 == null)) {
Temporary1 = "auto";
}
else {
Temporary1 = t_570425369;
}

setTheme(Temporary1);

function add_33556386(x_33556387, x_33556387_Idx, y_33556388) {
          if (x_33556387[x_33556387_Idx] === null) { x_33556387[x_33556387_Idx] = []; }
      var off = x_33556387[x_33556387_Idx].length;
      x_33556387[x_33556387_Idx].length += y_33556388.length;
      for (var i = 0; i < y_33556388.length; ++i) {
        x_33556387[x_33556387_Idx][off+i] = y_33556388.charCodeAt(i);
      }
    

  
}

function newSeq_33556765(len_33556767) {
  var result_33556768 = [];

    result_33556768 = new Array(len_33556767); for (var i = 0 ; i < len_33556767 ; ++i) { result_33556768[i] = null; }
  return result_33556768;

}

function unhandledException(e_33556603) {
    var buf_33556604 = [[]];
    if (!(((e_33556603.message).length == 0))) {
    buf_33556604[0].push.apply(buf_33556604[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    buf_33556604[0].push.apply(buf_33556604[0], e_33556603.message);;
    }
    else {
    buf_33556604[0].push.apply(buf_33556604[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    buf_33556604[0].push.apply(buf_33556604[0], [32,91]);;
    add_33556386(buf_33556604, 0, e_33556603.name);
    buf_33556604[0].push.apply(buf_33556604[0], [93,10]);;
    var cbuf_33556605 = toJSStr(buf_33556604[0]);
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556605);
  }
  else {
    throw cbuf_33556605;
  }
  

  
}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_33556881) {
        if (a_33556881 > 2147483647 || a_33556881 < -2147483648) raiseOverflow();
  

  
}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI134217751, name: null, trace: [], up: null}, "RangeDefect");

  
}

function addChars_301990066(result_301990068, result_301990068_Idx, x_301990069, start_301990070, n_301990071) {
    var Temporary1;

    var old_301990072 = (result_301990068[result_301990068_Idx]).length;
    if (result_301990068[result_301990068_Idx].length < (Temporary1 = chckRange(addInt(old_301990072, n_301990071), 0, 2147483647), Temporary1)) { for (var i = result_301990068[result_301990068_Idx].length; i < Temporary1; ++i) result_301990068[result_301990068_Idx].push(0); }
         else {result_301990068[result_301990068_Idx].length = Temporary1; };
    Label2: {
      var iHEX60gensym4_301990086 = 0;
      var i_570425443 = 0;
      Label3: {
          Label4: while (true) {
          if (!(i_570425443 < n_301990071)) break Label4;
            iHEX60gensym4_301990086 = i_570425443;
            result_301990068[result_301990068_Idx][chckIndx(addInt(old_301990072, iHEX60gensym4_301990086), 0, (result_301990068[result_301990068_Idx]).length - 1)] = x_301990069.charCodeAt(chckIndx(addInt(start_301990070, iHEX60gensym4_301990086), 0, (x_301990069).length - 1));
            i_570425443 = addInt(i_570425443, 1);
          }
      };
    };

  
}

function addChars_301990062(result_301990064, result_301990064_Idx, x_301990065) {
    addChars_301990066(result_301990064, result_301990064_Idx, x_301990065, 0, ((x_301990065) == null ? 0 : (x_301990065).length));

  
}

function addInt_301990087(result_301990088, result_301990088_Idx, x_301990089) {
    addChars_301990062(result_301990088, result_301990088_Idx, ((x_301990089) + ""));

  
}

function addInt_301990108(result_301990109, result_301990109_Idx, x_301990110) {
    addInt_301990087(result_301990109, result_301990109_Idx, x_301990110);

  
}

function HEX24_385875976(x_385875977) {
  var result_385875978 = [[]];

    addInt_301990108(result_385875978, 0, x_385875977);

  return result_385875978[0];

}

function isFatPointer_33557074(ti_33557075) {
  var result_33557076 = false;

  BeforeRet: {
    result_33557076 = !((ConstSet1[ti_33557075.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557076;

}

function nimCopyAux(dest_33557087, src_33557088, n_33557089) {
    switch (n_33557089.kind) {
    case 0:
      break;
    case 1:
            dest_33557087[n_33557089.offset] = nimCopy(dest_33557087[n_33557089.offset], src_33557088[n_33557089.offset], n_33557089.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_33557089.sons.length; i++) {
      nimCopyAux(dest_33557087, src_33557088, n_33557089.sons[i]);
    }
    
      break;
    case 3:
            dest_33557087[n_33557089.offset] = nimCopy(dest_33557087[n_33557089.offset], src_33557088[n_33557089.offset], n_33557089.typ);
      for (var i = 0; i < n_33557089.sons.length; ++i) {
        nimCopyAux(dest_33557087, src_33557088, n_33557089.sons[i][1]);
      }
    
      break;
    }

  
}

function raiseIndexError(i_33556694, a_33556695, b_33556696) {
    var Temporary1;

    if ((b_33556696 < a_33556695)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32] || []).concat(HEX24_385875976(i_33556694) || [],[32,110,111,116,32,105,110,32] || [],HEX24_385875976(a_33556695) || [],[32,46,46,32] || [],HEX24_385875976(b_33556696) || []);
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}

function sysFatal_268435493(message_268435496) {
    raiseException({message: nimCopy(null, message_268435496, NTI33554449), m_type: NTI134217745, parent: null, name: null, trace: [], up: null}, "AssertionDefect");

  
}

function raiseAssert_268435491(msg_268435492) {
    sysFatal_268435493(msg_268435492);

  
}

function failedAssertImpl_268435515(msg_268435516) {
    raiseAssert_268435491(msg_268435516);

  
}

function onDOMLoaded(e_570425371) {
            
function HEX3Aanonymous_570425395(event_570425396) {
                event_570425396.target.parentNode.style.display = "none";
                event_570425396.target.parentNode.nextSibling.style.display = "inline";

              
            }

    document.getElementById("theme-select").value = window.localStorage.getItem("theme");
    Label1: {
      var pragmaDots_570425394 = null;
      var colontmp__570425434 = [];
      colontmp__570425434 = document.getElementsByClassName("pragmadots");
      var i_570425436 = 0;
      var L_570425437 = (colontmp__570425434).length;
      Label2: {
          Label3: while (true) {
          if (!(i_570425436 < L_570425437)) break Label3;
            pragmaDots_570425394 = colontmp__570425434[chckIndx(i_570425436, 0, (colontmp__570425434).length - 1)];
            pragmaDots_570425394.onclick = HEX3Aanonymous_570425395;
            i_570425436 = addInt(i_570425436, 1);
            if (!(((colontmp__570425434).length == L_570425437))) {
            failedAssertImpl_268435515(makeNimstrLit("iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };

  
}
var alternative_570425933 = [null];

function isWhitespace_570425679(x_570425680) {
  var result_570425681 = false;

    result_570425681 = (((x_570425680.nodeName == "#text") && !/\S/.test(x_570425680.textContent)) || (x_570425680.nodeName == "#comment"));

  return result_570425681;

}

function toToc_570425682(x_570425683, father_570425684) {
                var Temporary5;
            var Temporary6;
            var Temporary7;
            var Temporary8;
      var Temporary15;

    if ((x_570425683.nodeName == "UL")) {
    var f_570425692 = {heading: null, kids: [], sortId: (father_570425684.kids).length, doSort: false};
    var i_570425693 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_570425693 < x_570425683.childNodes.length)) break Label2;
          var nxt_570425694 = addInt(i_570425693, 1);
          Label3: {
              Label4: while (true) {
                if (!(nxt_570425694 < x_570425683.childNodes.length)) Temporary5 = false; else {                  Temporary5 = isWhitespace_570425679(x_570425683.childNodes[nxt_570425694]);                }              if (!Temporary5) break Label4;
                nxt_570425694 = addInt(nxt_570425694, 1);
              }
          };
            if (!(nxt_570425694 < x_570425683.childNodes.length)) Temporary8 = false; else {              Temporary8 = (x_570425683.childNodes[i_570425693].nodeName == "LI");            }            if (!Temporary8) Temporary7 = false; else {              Temporary7 = (x_570425683.childNodes[i_570425693].childNodes.length == 1);            }            if (!Temporary7) Temporary6 = false; else {              Temporary6 = (x_570425683.childNodes[nxt_570425694].nodeName == "UL");            }          if (Temporary6) {
          var e_570425707 = {heading: x_570425683.childNodes[i_570425693].childNodes[0], kids: [], sortId: (f_570425692.kids).length, doSort: false};
          var it_570425708 = x_570425683.childNodes[nxt_570425694];
          Label9: {
            var j_570425713 = 0;
            var colontmp__570425971 = 0;
            colontmp__570425971 = it_570425708.childNodes.length;
            var i_570425972 = 0;
            Label10: {
                Label11: while (true) {
                if (!(i_570425972 < colontmp__570425971)) break Label11;
                  j_570425713 = i_570425972;
                  toToc_570425682(it_570425708.childNodes[j_570425713], e_570425707);
                  i_570425972 = addInt(i_570425972, 1);
                }
            };
          };
          f_570425692.kids.push(e_570425707);;
          i_570425693 = addInt(nxt_570425694, 1);
          }
          else {
            toToc_570425682(x_570425683.childNodes[i_570425693], f_570425692);
            i_570425693 = addInt(i_570425693, 1);
          }
          
        }
    };
    father_570425684.kids.push(f_570425692);;
    }
    else {
    if (isWhitespace_570425679(x_570425683)) {
    }
    else {
    if ((x_570425683.nodeName == "LI")) {
    var idx_570425731 = [];
    Label12: {
      var i_570425736 = 0;
      var colontmp__570425975 = 0;
      colontmp__570425975 = x_570425683.childNodes.length;
      var i_570425976 = 0;
      Label13: {
          Label14: while (true) {
          if (!(i_570425976 < colontmp__570425975)) break Label14;
            i_570425736 = i_570425976;
            if (!(isWhitespace_570425679(x_570425683.childNodes[i_570425736]))) {
            idx_570425731.push(i_570425736);;
            }
            
            i_570425976 = addInt(i_570425976, 1);
          }
      };
    };
      if (!((idx_570425731).length == 2)) Temporary15 = false; else {        Temporary15 = (x_570425683.childNodes[idx_570425731[chckIndx(1, 0, (idx_570425731).length - 1)]].nodeName == "UL");      }    if (Temporary15) {
    var e_570425752 = {heading: x_570425683.childNodes[idx_570425731[chckIndx(0, 0, (idx_570425731).length - 1)]], kids: [], sortId: (father_570425684.kids).length, doSort: false};
    var it_570425753 = x_570425683.childNodes[idx_570425731[chckIndx(1, 0, (idx_570425731).length - 1)]];
    Label16: {
      var j_570425758 = 0;
      var colontmp__570425979 = 0;
      colontmp__570425979 = it_570425753.childNodes.length;
      var i_570425980 = 0;
      Label17: {
          Label18: while (true) {
          if (!(i_570425980 < colontmp__570425979)) break Label18;
            j_570425758 = i_570425980;
            toToc_570425682(it_570425753.childNodes[j_570425758], e_570425752);
            i_570425980 = addInt(i_570425980, 1);
          }
      };
    };
    father_570425684.kids.push(e_570425752);;
    }
    else {
      Label19: {
        var i_570425767 = 0;
        var colontmp__570425983 = 0;
        colontmp__570425983 = x_570425683.childNodes.length;
        var i_570425984 = 0;
        Label20: {
            Label21: while (true) {
            if (!(i_570425984 < colontmp__570425983)) break Label21;
              i_570425767 = i_570425984;
              toToc_570425682(x_570425683.childNodes[i_570425767], father_570425684);
              i_570425984 = addInt(i_570425984, 1);
            }
        };
      };
    }
    
    }
    else {
    father_570425684.kids.push({heading: x_570425683, kids: [], sortId: (father_570425684.kids).length, doSort: false});;
    }
    }}

  
}

function extractItems_570425516(x_570425517, heading_570425518, items_570425519, items_570425519_Idx) {
  BeforeRet: {
    if ((x_570425517 == null)) {
    break BeforeRet;
    }
    
    if ((!((x_570425517.heading == null)) && (x_570425517.heading.textContent == heading_570425518))) {
    Label1: {
      var i_570425536 = 0;
      var colontmp__570425987 = 0;
      colontmp__570425987 = (x_570425517.kids).length;
      var i_570425988 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570425988 < colontmp__570425987)) break Label3;
            i_570425536 = i_570425988;
            items_570425519[items_570425519_Idx].push(x_570425517.kids[chckIndx(i_570425536, 0, (x_570425517.kids).length - 1)].heading);;
            i_570425988 = addInt(i_570425988, 1);
          }
      };
    };
    }
    else {
      Label4: {
        var k_570425562 = null;
        var i_570425992 = 0;
        var L_570425993 = (x_570425517.kids).length;
        Label5: {
            Label6: while (true) {
            if (!(i_570425992 < L_570425993)) break Label6;
              k_570425562 = x_570425517.kids[chckIndx(i_570425992, 0, (x_570425517.kids).length - 1)];
              extractItems_570425516(k_570425562, heading_570425518, items_570425519, items_570425519_Idx);
              i_570425992 = addInt(i_570425992, 1);
              if (!(((x_570425517.kids).length == L_570425993))) {
              failedAssertImpl_268435515(makeNimstrLit("iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it"));
              }
              
            }
        };
      };
    }
    
  };

  
}

function tree_570425447(tag_570425448, kids_570425449) {
  var result_570425450 = null;

    result_570425450 = document.createElement(tag_570425448);
    Label1: {
      var k_570425464 = null;
      var i_570426005 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570426005 < (kids_570425449).length)) break Label3;
            k_570425464 = kids_570425449[chckIndx(i_570426005, 0, (kids_570425449).length - 1)];
            result_570425450.appendChild(k_570425464);
            i_570426005 = addInt(i_570426005, 1);
          }
      };
    };

  return result_570425450;

}

function text_570425472(s_570425473) {
  var result_570425474 = null;

    result_570425474 = document.createTextNode(s_570425473);

  return result_570425474;

}

function uncovered_570425833(x_570425834) {
    var Temporary1;

  var result_570425835 = null;

  BeforeRet: {
    if ((((x_570425834.kids).length == 0) && !((x_570425834.heading == null)))) {
    if (!(x_570425834.heading.hasOwnProperty('__karaxMarker__'))) {
    Temporary1 = x_570425834;
    }
    else {
    Temporary1 = null;
    }
    
    result_570425835 = Temporary1;
    break BeforeRet;
    }
    
    result_570425835 = {heading: x_570425834.heading, kids: [], sortId: x_570425834.sortId, doSort: x_570425834.doSort};
    Label2: {
      var k_570425850 = null;
      var i_570426012 = 0;
      var L_570426013 = (x_570425834.kids).length;
      Label3: {
          Label4: while (true) {
          if (!(i_570426012 < L_570426013)) break Label4;
            k_570425850 = x_570425834.kids[chckIndx(i_570426012, 0, (x_570425834.kids).length - 1)];
            var y_570425851 = uncovered_570425833(k_570425850);
            if (!((y_570425851 == null))) {
            result_570425835.kids.push(y_570425851);;
            }
            
            i_570426012 = addInt(i_570426012, 1);
            if (!(((x_570425834.kids).length == L_570426013))) {
            failedAssertImpl_268435515(makeNimstrLit("iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    if (((result_570425835.kids).length == 0)) {
    result_570425835 = null;
    }
    
  };

  return result_570425835;

}

function mergeTocs_570425863(orig_570425864, news_570425865) {
  var result_570425866 = null;

    result_570425866 = uncovered_570425833(orig_570425864);
    if ((result_570425866 == null)) {
    result_570425866 = news_570425865;
    }
    else {
      Label1: {
        var i_570425878 = 0;
        var colontmp__570426008 = 0;
        colontmp__570426008 = (news_570425865.kids).length;
        var i_570426009 = 0;
        Label2: {
            Label3: while (true) {
            if (!(i_570426009 < colontmp__570426008)) break Label3;
              i_570425878 = i_570426009;
              result_570425866.kids.push(news_570425865.kids[chckIndx(i_570425878, 0, (news_570425865.kids).length - 1)]);;
              i_570426009 = addInt(i_570426009, 1);
            }
        };
      };
    }
    

  return result_570425866;

}

function buildToc_570425883(orig_570425884, types_570425885, procs_570425886) {
  var result_570425887 = null;

    var newStuff_570425892 = {heading: null, kids: [], doSort: true, sortId: 0};
    Label1: {
      var t_570425896 = null;
      var i_570426000 = 0;
      var L_570426001 = (types_570425885).length;
      Label2: {
          Label3: while (true) {
          if (!(i_570426000 < L_570426001)) break Label3;
            t_570425896 = types_570425885[chckIndx(i_570426000, 0, (types_570425885).length - 1)];
            var c_570425901 = {heading: t_570425896.cloneNode(true), kids: [], doSort: true, sortId: 0};
            t_570425896.__karaxMarker__ = true;
            Label4: {
              var p_570425905 = null;
              var i_570425997 = 0;
              var L_570425998 = (procs_570425886).length;
              Label5: {
                  Label6: while (true) {
                  if (!(i_570425997 < L_570425998)) break Label6;
                    p_570425905 = procs_570425886[chckIndx(i_570425997, 0, (procs_570425886).length - 1)];
                    if (!(p_570425905.hasOwnProperty('__karaxMarker__'))) {
                    var xx_570425906 = p_570425905.parentNode.getElementsByClassName("attachedType");
                    if ((((xx_570425906).length == 1) && (xx_570425906[chckIndx(0, 0, (xx_570425906).length - 1)].textContent == t_570425896.textContent))) {
                    var q_570425911 = tree_570425447("A", [text_570425472(p_570425905.title)]);
                    q_570425911.setAttribute("href", p_570425905.getAttribute("href"));
                    c_570425901.kids.push({heading: q_570425911, kids: [], sortId: 0, doSort: false});;
                    p_570425905.__karaxMarker__ = true;
                    }
                    
                    }
                    
                    i_570425997 = addInt(i_570425997, 1);
                    if (!(((procs_570425886).length == L_570425998))) {
                    failedAssertImpl_268435515(makeNimstrLit("iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it"));
                    }
                    
                  }
              };
            };
            newStuff_570425892.kids.push(c_570425901);;
            i_570426000 = addInt(i_570426000, 1);
            if (!(((types_570425885).length == L_570426001))) {
            failedAssertImpl_268435515(makeNimstrLit("iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    result_570425887 = mergeTocs_570425863(orig_570425884, newStuff_570425892);

  return result_570425887;

}

function add_570425465(parent_570425466, kid_570425467) {
    if (((parent_570425466.nodeName == "TR") && ((kid_570425467.nodeName == "TD") || (kid_570425467.nodeName == "TH")))) {
    var k_570425468 = document.createElement("TD");
    k_570425468.appendChild(kid_570425467);
    parent_570425466.appendChild(k_570425468);
    }
    else {
    parent_570425466.appendChild(kid_570425467);
    }
    

  
}

function setClass_570425469(e_570425470, value_570425471) {
    e_570425470.setAttribute("class", value_570425471);

  
}

function toHtml_570425581(x_570425582, isRoot_570425583) {
    
function HEX3Aanonymous_570425601(a_570425602, b_570425603) {
      var result_570425604 = 0;

      BeforeRet: {
        if ((!((a_570425602.heading == null)) && !((b_570425603.heading == null)))) {
        var x_570425613 = a_570425602.heading.textContent;
        var y_570425614 = b_570425603.heading.textContent;
        if ((x_570425613 < y_570425614)) {
        result_570425604 = -1;
        break BeforeRet;
        }
        
        if ((y_570425614 < x_570425613)) {
        result_570425604 = 1;
        break BeforeRet;
        }
        
        result_570425604 = 0;
        break BeforeRet;
        }
        else {
          result_570425604 = subInt(a_570425602.sortId, b_570425603.sortId);
          break BeforeRet;
        }
        
      };

      return result_570425604;

    }

  var result_570425584 = null;

  BeforeRet: {
    if ((x_570425582 == null)) {
    result_570425584 = null;
    break BeforeRet;
    }
    
    if (((x_570425582.kids).length == 0)) {
    if ((x_570425582.heading == null)) {
    result_570425584 = null;
    break BeforeRet;
    }
    
    result_570425584 = x_570425582.heading.cloneNode(true);
    break BeforeRet;
    }
    
    result_570425584 = tree_570425447("DIV", []);
    if ((!((x_570425582.heading == null)) && !(x_570425582.heading.hasOwnProperty('__karaxMarker__')))) {
    add_570425465(result_570425584, x_570425582.heading.cloneNode(true));
    }
    
    var ul_570425600 = tree_570425447("UL", []);
    if (isRoot_570425583) {
    setClass_570425469(ul_570425600, "simple simple-toc");
    }
    else {
    setClass_570425469(ul_570425600, "simple");
    }
    
    if (x_570425582.doSort) {
    x_570425582.kids.sort(HEX3Aanonymous_570425601);
    }
    
    Label1: {
      var k_570425626 = null;
      var i_570426016 = 0;
      var L_570426017 = (x_570425582.kids).length;
      Label2: {
          Label3: while (true) {
          if (!(i_570426016 < L_570426017)) break Label3;
            k_570425626 = x_570425582.kids[chckIndx(i_570426016, 0, (x_570425582.kids).length - 1)];
            var y_570425627 = toHtml_570425581(k_570425626, false);
            if (!((y_570425627 == null))) {
            add_570425465(ul_570425600, tree_570425447("LI", [y_570425627]));
            }
            
            i_570426016 = addInt(i_570426016, 1);
            if (!(((x_570425582.kids).length == L_570426017))) {
            failedAssertImpl_268435515(makeNimstrLit("iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    if (!((ul_570425600.childNodes.length == 0))) {
    add_570425465(result_570425584, ul_570425600);
    }
    
    if ((result_570425584.childNodes.length == 0)) {
    result_570425584 = null;
    }
    
  };

  return result_570425584;

}

function replaceById_570425475(id_570425476, newTree_570425477) {
    var x_570425478 = document.getElementById(id_570425476);
    x_570425478.parentNode.replaceChild(newTree_570425477, x_570425478);
    newTree_570425477.id = id_570425476;

  
}

function togglevis_570425934(d_570425935) {
    if ((d_570425935.style.display == "none")) {
    d_570425935.style.display = "inline";
    }
    else {
      d_570425935.style.display = "none";
    }
    

  
}

function groupBy(value_570425937) {
    var toc_570425938 = document.getElementById("toc-list");
    if ((alternative_570425933[0] == null)) {
    var tt_570425946 = {heading: null, kids: [], sortId: 0, doSort: false};
    toToc_570425682(toc_570425938, tt_570425946);
    tt_570425946 = tt_570425946.kids[chckIndx(0, 0, (tt_570425946.kids).length - 1)];
    var types_570425951 = [[]];
    var procs_570425956 = [[]];
    extractItems_570425516(tt_570425946, "Types", types_570425951, 0);
    extractItems_570425516(tt_570425946, "Procs", procs_570425956, 0);
    extractItems_570425516(tt_570425946, "Converters", procs_570425956, 0);
    extractItems_570425516(tt_570425946, "Methods", procs_570425956, 0);
    extractItems_570425516(tt_570425946, "Templates", procs_570425956, 0);
    extractItems_570425516(tt_570425946, "Macros", procs_570425956, 0);
    extractItems_570425516(tt_570425946, "Iterators", procs_570425956, 0);
    var ntoc_570425957 = buildToc_570425883(tt_570425946, types_570425951[0], procs_570425956[0]);
    var x_570425958 = toHtml_570425581(ntoc_570425957, true);
    alternative_570425933[0] = tree_570425447("DIV", [x_570425958]);
    }
    
    if ((value_570425937 == "type")) {
    replaceById_570425475("tocRoot", alternative_570425933[0]);
    }
    else {
    replaceById_570425475("tocRoot", tree_570425447("DIV", []));
    }
    
    togglevis_570425934(document.getElementById("toc-list"));

  
}
var db_570426019 = [[]];
var contents_570426020 = [[]];
var oldtoc_570426277 = [null];
var timer_570426278 = [null];
var loadIndexFut_570426280 = [null];

function HEX5BHEX5D_738198807(s_738198810, x_738198811) {
  var result_738198812 = [];

    var a_738198814 = x_738198811.a;
    var L_738198816 = addInt(subInt(subInt((s_738198810).length, x_738198811.b), a_738198814), 1);
    result_738198812 = nimCopy(null, mnewString(chckRange(L_738198816, 0, 2147483647)), NTI33554449);
    Label1: {
      var i_738198821 = 0;
      var i_570426352 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570426352 < L_738198816)) break Label3;
            i_738198821 = i_570426352;
            result_738198812[chckIndx(i_738198821, 0, (result_738198812).length - 1)] = s_738198810[chckIndx(addInt(i_738198821, a_738198814), 0, (s_738198810).length - 1)];
            i_570426352 = addInt(i_570426352, 1);
          }
      };
    };

  return result_738198812;

}

function HEX2EHEX2E_973078624(a_973078627, b_973078628) {
  var result_973078631 = ({a: 0, b: 0});

    result_973078631 = nimCopy(result_973078631, {a: a_973078627, b: b_973078628}, NTI973078612);

  return result_973078631;

}
async function loadIndex_570426154() {
  var result_570426156 = null;

  BeforeRet: {
    var indexURL_570426162 = document.getElementById("indexLink").getAttribute("href");
    var rootURL_570426188 = HEX5BHEX5D_738198807(cstrToNimstr(indexURL_570426162), HEX2EHEX2E_973078624(0, 14));
    var resp_570426200 = (await (await fetch(indexURL_570426162)).text());
    var indexElem_570426201 = document.createElement("div");
    indexElem_570426201.innerHTML = resp_570426200;
    Label1: {
      var href_570426223 = null;
      var colontmp__570426346 = [];
      colontmp__570426346 = indexElem_570426201.getElementsByClassName("reference");
      var i_570426348 = 0;
      var L_570426349 = (colontmp__570426346).length;
      Label2: {
          Label3: while (true) {
          if (!(i_570426348 < L_570426349)) break Label3;
            href_570426223 = colontmp__570426346[chckIndx(i_570426348, 0, (colontmp__570426346).length - 1)];
            href_570426223.setAttribute("href", toJSStr((rootURL_570426188 || []).concat(cstrToNimstr(href_570426223.getAttribute("href")) || [])));
            db_570426019[0].push(href_570426223);;
            contents_570426020[0].push(href_570426223.getAttribute("data-doc-search-tag"));;
            i_570426348 = addInt(i_570426348, 1);
            if (!(((colontmp__570426346).length == L_570426349))) {
            failedAssertImpl_268435515(makeNimstrLit("iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    result_570426156 = undefined;
    break BeforeRet;
  };

  return result_570426156;

}

function then_570426306(future_570426309, onSuccess_570426310, onReject_570426311) {
  var result_570426312 = null;

  BeforeRet: {
    var ret_570426322 = null;
    ret_570426322 = future_570426309.then(onSuccess_570426310, onReject_570426311)
    result_570426312 = ret_570426322;
    break BeforeRet;
  };

  return result_570426312;

}

function nsuToLowerAsciiChar(c_738197588) {
  var result_738197589 = 0;

    if ((ConstSet2[c_738197588] != undefined)) {
    result_738197589 = (c_738197588 ^ 32);
    }
    else {
      result_738197589 = c_738197588;
    }
    

  return result_738197589;

}

function fuzzyMatch_721420304(pattern_721420305, str_721420306) {
              var Temporary4;
              var Temporary5;
                var Temporary6;
      var Temporary7;
        var Temporary8;

  var result_721420309 = {Field0: 0, Field1: false};

    var scoreState_721420310 = -100;
    var headerMatched_721420311 = false;
    var unmatchedLeadingCharCount_721420312 = 0;
    var consecutiveMatchCount_721420313 = 0;
    var strIndex_721420314 = 0;
    var patIndex_721420315 = 0;
    var score_721420316 = 0;
    Label1: {
        Label2: while (true) {
        if (!((strIndex_721420314 < ((str_721420306) == null ? 0 : (str_721420306).length)) && (patIndex_721420315 < ((pattern_721420305) == null ? 0 : (pattern_721420305).length)))) break Label2;
          Label3: {
            var patternChar_721420319 = nsuToLowerAsciiChar(pattern_721420305.charCodeAt(chckIndx(patIndex_721420315, 0, (pattern_721420305).length - 1)));
            var strChar_721420320 = nsuToLowerAsciiChar(str_721420306.charCodeAt(chckIndx(strIndex_721420314, 0, (str_721420306).length - 1)));
            if ((ConstSet3[patternChar_721420319] != undefined)) {
            patIndex_721420315 = addInt(patIndex_721420315, 1);
            break Label3;
            }
            
            if ((ConstSet4[strChar_721420320] != undefined)) {
            strIndex_721420314 = addInt(strIndex_721420314, 1);
            break Label3;
            }
            
            if ((!(headerMatched_721420311) && (strChar_721420320 == 58))) {
            headerMatched_721420311 = true;
            scoreState_721420310 = -100;
            score_721420316 = ((Math.floor((0.5 * score_721420316))) | 0);
            patIndex_721420315 = 0;
            strIndex_721420314 = addInt(strIndex_721420314, 1);
            break Label3;
            }
            
            if ((strChar_721420320 == patternChar_721420319)) {
            switch (scoreState_721420310) {
            case -100:
            case 20:
              scoreState_721420310 = 10;
              break;
            case 0:
              scoreState_721420310 = 5;
              score_721420316 = addInt(score_721420316, scoreState_721420310);
              break;
            case 10:
            case 5:
              consecutiveMatchCount_721420313 = addInt(consecutiveMatchCount_721420313, 1);
              scoreState_721420310 = 5;
              score_721420316 = addInt(score_721420316, mulInt(5, consecutiveMatchCount_721420313));
              if ((scoreState_721420310 == 10)) {
              score_721420316 = addInt(score_721420316, 10);
              }
              
              var onBoundary_721420372 = (patIndex_721420315 == ((pattern_721420305) == null ? -1 : (pattern_721420305).length - 1));
              if ((!(onBoundary_721420372) && (strIndex_721420314 < ((str_721420306) == null ? -1 : (str_721420306).length - 1)))) {
              var nextPatternChar_721420373 = nsuToLowerAsciiChar(pattern_721420305.charCodeAt(chckIndx(addInt(patIndex_721420315, 1), 0, (pattern_721420305).length - 1)));
              var nextStrChar_721420374 = nsuToLowerAsciiChar(str_721420306.charCodeAt(chckIndx(addInt(strIndex_721420314, 1), 0, (str_721420306).length - 1)));
              if (!!((ConstSet5[nextStrChar_721420374] != undefined))) Temporary4 = false; else {                Temporary4 = !((nextStrChar_721420374 == nextPatternChar_721420373));              }              onBoundary_721420372 = Temporary4;
              }
              
              if (onBoundary_721420372) {
              scoreState_721420310 = 20;
              score_721420316 = addInt(score_721420316, scoreState_721420310);
              }
              
              break;
            case -1:
            case -3:
              if (!((ConstSet6[str_721420306.charCodeAt(chckIndx(subInt(strIndex_721420314, 1), 0, (str_721420306).length - 1))] != undefined))) Temporary5 = true; else {                if (!(ConstSet7[str_721420306.charCodeAt(chckIndx(subInt(strIndex_721420314, 1), 0, (str_721420306).length - 1))] != undefined)) Temporary6 = false; else {                  Temporary6 = (ConstSet8[str_721420306.charCodeAt(chckIndx(strIndex_721420314, 0, (str_721420306).length - 1))] != undefined);                }                Temporary5 = Temporary6;              }              var isLeadingChar_721420398 = Temporary5;
              if (isLeadingChar_721420398) {
              scoreState_721420310 = 10;
              }
              else {
                scoreState_721420310 = 0;
                score_721420316 = addInt(score_721420316, scoreState_721420310);
              }
              
              break;
            }
            patIndex_721420315 = addInt(patIndex_721420315, 1);
            }
            else {
              switch (scoreState_721420310) {
              case -100:
                scoreState_721420310 = -3;
                score_721420316 = addInt(score_721420316, scoreState_721420310);
                break;
              case 5:
                scoreState_721420310 = -1;
                score_721420316 = addInt(score_721420316, scoreState_721420310);
                consecutiveMatchCount_721420313 = 0;
                break;
              case -3:
                if ((unmatchedLeadingCharCount_721420312 < 3)) {
                scoreState_721420310 = -3;
                score_721420316 = addInt(score_721420316, scoreState_721420310);
                }
                
                unmatchedLeadingCharCount_721420312 = addInt(unmatchedLeadingCharCount_721420312, 1);
                break;
              default: 
                scoreState_721420310 = -1;
                score_721420316 = addInt(score_721420316, scoreState_721420310);
                break;
              }
            }
            
            strIndex_721420314 = addInt(strIndex_721420314, 1);
          };
        }
    };
      if (!(patIndex_721420315 == ((pattern_721420305) == null ? 0 : (pattern_721420305).length))) Temporary7 = false; else {        if ((strIndex_721420314 == ((str_721420306) == null ? 0 : (str_721420306).length))) Temporary8 = true; else {          Temporary8 = !((ConstSet9[str_721420306.charCodeAt(chckIndx(strIndex_721420314, 0, (str_721420306).length - 1))] != undefined));        }        Temporary7 = Temporary8;      }    if (Temporary7) {
    score_721420316 = addInt(score_721420316, 10);
    }
    
    var colontmp__570426366 = nimMax(0, score_721420316);
    var colontmp__570426367 = (0 < score_721420316);
    result_721420309 = nimCopy(result_721420309, {Field0: colontmp__570426366, Field1: colontmp__570426367}, NTI721420302);

  return result_721420309;

}

function escapeCString_570426021(x_570426022, x_570426022_Idx) {
    var s_570426023 = [];
    Label1: {
      var c_570426024 = 0;
      var iHEX60gensym6_570426370 = 0;
      var nHEX60gensym6_570426371 = ((x_570426022[x_570426022_Idx]) == null ? 0 : (x_570426022[x_570426022_Idx]).length);
      Label2: {
          Label3: while (true) {
          if (!(iHEX60gensym6_570426370 < nHEX60gensym6_570426371)) break Label3;
            c_570426024 = x_570426022[x_570426022_Idx].charCodeAt(chckIndx(iHEX60gensym6_570426370, 0, (x_570426022[x_570426022_Idx]).length - 1));
            switch (c_570426024) {
            case 60:
              s_570426023.push.apply(s_570426023, [38,108,116,59]);;
              break;
            case 62:
              s_570426023.push.apply(s_570426023, [38,103,116,59]);;
              break;
            default: 
              addChar(s_570426023, c_570426024);;
              break;
            }
            iHEX60gensym6_570426370 = addInt(iHEX60gensym6_570426370, 1);
          }
      };
    };
    x_570426022[x_570426022_Idx] = toJSStr(s_570426023);

  
}

function dosearch_570426025(value_570426026) {
    
function HEX3Aanonymous_570426052(a_570426057, b_570426058) {
      var result_570426063 = 0;

        result_570426063 = subInt(b_570426058["Field1"], a_570426057["Field1"]);

      return result_570426063;

    }

  var result_570426027 = null;

  BeforeRet: {
    if (((db_570426019[0]).length == 0)) {
    break BeforeRet;
    }
    
    var ul_570426031 = tree_570425447("UL", []);
    result_570426027 = tree_570425447("DIV", []);
    setClass_570425469(result_570426027, "search_results");
    var matches_570426036 = [];
    Label1: {
      var i_570426044 = 0;
      var colontmp__570426356 = 0;
      colontmp__570426356 = (db_570426019[0]).length;
      var i_570426357 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570426357 < colontmp__570426356)) break Label3;
            i_570426044 = i_570426357;
            Label4: {
              var c_570426045 = contents_570426020[0][chckIndx(i_570426044, 0, (contents_570426020[0]).length - 1)];
              if (((c_570426045 == "Examples") || (c_570426045 == "PEG construction"))) {
              break Label4;
              }
              
              var colontmp__570426363 = fuzzyMatch_721420304(value_570426026, c_570426045);
              var score_570426046 = colontmp__570426363["Field0"];
              var matched_570426047 = colontmp__570426363["Field1"];
              if (matched_570426047) {
              matches_570426036.push({Field0: db_570426019[0][chckIndx(i_570426044, 0, (db_570426019[0]).length - 1)], Field1: score_570426046});;
              }
              
            };
            i_570426357 = addInt(i_570426357, 1);
          }
      };
    };
    matches_570426036.sort(HEX3Aanonymous_570426052);
    Label5: {
      var i_570426080 = 0;
      var colontmp__570426360 = 0;
      colontmp__570426360 = nimMin((matches_570426036).length, 29);
      var i_570426361 = 0;
      Label6: {
          Label7: while (true) {
          if (!(i_570426361 < colontmp__570426360)) break Label7;
            i_570426080 = i_570426361;
            matches_570426036[chckIndx(i_570426080, 0, (matches_570426036).length - 1)]["Field0"].innerHTML = matches_570426036[chckIndx(i_570426080, 0, (matches_570426036).length - 1)]["Field0"].getAttribute("data-doc-search-tag");
            escapeCString_570426021(matches_570426036[chckIndx(i_570426080, 0, (matches_570426036).length - 1)]["Field0"], "innerHTML");
            add_570425465(ul_570426031, tree_570425447("LI", [matches_570426036[chckIndx(i_570426080, 0, (matches_570426036).length - 1)]["Field0"]]));
            i_570426361 = addInt(i_570426361, 1);
          }
      };
    };
    if ((ul_570426031.childNodes.length == 0)) {
    add_570425465(result_570426027, tree_570425447("B", [text_570425472("no search results")]));
    }
    else {
      add_570425465(result_570426027, tree_570425447("B", [text_570425472("search results")]));
      add_570425465(result_570426027, ul_570426031);
    }
    
  };

  return result_570426027;

}

function search() {
    
function wrapper_570426291() {
        var elem_570426292 = document.getElementById("searchInput");
        var value_570426293 = elem_570426292.value;
        if (!((((value_570426293) == null ? 0 : (value_570426293).length) == 0))) {
        if ((oldtoc_570426277[0] == null)) {
        oldtoc_570426277[0] = document.getElementById("tocRoot");
        }
        
        var results_570426297 = dosearch_570426025(value_570426293);
        replaceById_570425475("tocRoot", results_570426297);
        }
        else {
        if (!((oldtoc_570426277[0] == null))) {
        replaceById_570425475("tocRoot", oldtoc_570426277[0]);
        }
        }

      
    }

    if ((loadIndexFut_570426280[0] == null)) {
    loadIndexFut_570426280[0] = loadIndex_570426154();
    var _ = then_570426306(loadIndexFut_570426280[0], wrapper_570426291, null);
    }
    
    if (!((timer_570426278[0] == null))) {
    clearTimeout(timer_570426278[0]);
    }
    
    timer_570426278[0] = setTimeout(wrapper_570426291, 400);

  
}

function copyToClipboard() {
    
    function updatePreTags() {

      const allPreTags = document.querySelectorAll("pre")
    
      allPreTags.forEach((e) => {
      
          const div = document.createElement("div")
          div.classList.add("copyToClipBoard")
    
          const preTag = document.createElement("pre")
          preTag.innerHTML = e.innerHTML
    
          const button = document.createElement("button")
          button.value = e.textContent.replace('...', '') 
          button.classList.add("copyToClipBoardBtn")
          button.style.cursor = "pointer"
    
          div.appendChild(preTag)
          div.appendChild(button)
    
          e.outerHTML = div.outerHTML
      
      })
    }


    function copyTextToClipboard(e) {
        const clipBoardContent = e.target.value
        navigator.clipboard.writeText(clipBoardContent).then(function() {
            e.target.style.setProperty("--clipboard-image", "var(--clipboard-image-selected)")
        }, function(err) {
            console.error("Could not copy text: ", err);
        });
    }

    window.addEventListener("click", (e) => {
        if (e.target.classList.contains("copyToClipBoardBtn")) {
            copyTextToClipboard(e)
          }
    })

    window.addEventListener("mouseover", (e) => {
        if (e.target.nodeName === "PRE") {
            e.target.nextElementSibling.style.setProperty("--clipboard-image", "var(--clipboard-image-normal)")
        }
    })
    
    window.addEventListener("DOMContentLoaded", updatePreTags)

    

  
}
copyToClipboard();
window.addEventListener("DOMContentLoaded", onDOMLoaded, false);
